CREATE TABLE usuario(
  USR_CodigoUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USR_Nome VARCHAR(250),
  USR_Email VARCHAR(250),
  USR_Nivel INT,
  USR_Senha VARCHAR(250)
);

CREATE TABLE categorias(
  CAT_CodigoCategoria INT AUTO_INCREMENT PRIMARY KEY,
  CAT_Nome VARCHAR(250),
  CAT_CodigoMarca INT,
  CAT_Status INT DEFAULT 1,
  CAT_Imagem VARCHAR(250),
  FOREIGN KEY (CAT_CodigoMarca) REFERENCES marcas(MAR_CodigoMarca)
);

CREATE TABLE produtos(
  PRO_CodigoProduto INT AUTO_INCREMENT PRIMARY KEY,
  PRO_CodigoCategoria INT,
  PRO_CodigoMarca INT,
  PRO_Nome VARCHAR(150),
  PRO_Descricao LONGTEXT,
  PRO_Peso VARCHAR(250),
  PRO_Avisos LONGTEXT,
  PRO_Status INT,
  PRO_URL VARCHAR(250),
  PRO_SEO LONGTEXT,
  PRO_MetaDados LONGTEXT,
  PRO_DataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRO_CodigoCategoria) REFERENCES marcas(MAR_CodigoMarca)
);

CREATE TABLE produtos_imagem(
  IMG_CodigoImagem INT AUTO_INCREMENT PRIMARY KEY,
  IMG_Imagem VARCHAR(500),
  IMG_CodigoProduto INT,
  FOREIGN KEY (IMG_CodigoProduto) REFERENCES produtos(PRO_CodigoProduto)
);

CREATE TABLE lead(
  LE_CodigoLead INT AUTO_INCREMENT PRIMARY KEY,
  LE_Nome VARCHAR(250),
  LE_CodigoProduto INT,
  LE_Email VARCHAR(150),
  LE_Data DATETIME DEFAULT CURRENT_TIMESTAMP,
  LE_Status INT
);

CREATE TABLE temas(
  TEM_CodigoTema INT AUTO_INCREMENT PRIMARY KEY,
  TEM_Nome VARCHAR(150),
  TEM_Ref VARCHAR(150),
  TEM_MetaDados LONGTEXT
);

CREATE TABLE paginas(
  PAG_CodigoPagina INT AUTO_INCREMENT PRIMARY KEY,
  PAG_Nome VARCHAR(150),
  PAG_DataCriacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  PAG_Tipo INT,
  PAG_SEODescription VARCHAR(250),
  PAG_SEOKeywords VARCHAR(150),
  PAG_SEOTitle VARCHAR(150),
  PAG_URL VARCHAR(250),
  PAG_HTML LONGTEXT,
  PAG_Tema INT,
  PAG_Status INT DEFAULT 1,
  FOREIGN KEY (PAG_Tema) REFERENCES temas(TEM_CodigoTema)
);
